name: CICD Analyseur loto

permissions:
  issues: write
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - 'master'
      - 'develop'

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Terraform
    steps:
    - uses: actions/checkout@v2
  
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Sha declared
        id: var
        shell: bash
        run: echo '::set-output name=sha::${GITHUB_SHA::7}'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            maximaxft/analyseur-loto:latest.py
            maximaxft/analyseur-loto:${{ steps.var.outputs.sha }}.py
